# Site Settings
locale                   : "en-US"
title                    : "GgukGguk"
title_separator          : "-"
subtitle                 : policy
name                     : "GgukGguk"
description              : "An amazing website."
url                      : "ggukgguk.github.io"
baseurl                  : ""
